<?php
include "includes/userheader.php";
?>

<div class="container-fluid">
    <div class="layout-specing">
        <div class="d-flex align-items-center justify-content-between">
            <div>
                <h6 class="text-muted mb-1">Welcome back, Cristina!</h6>
                <h5 class="mb-0">Dashboard</h5>
            </div>

            <div class="mb-0 position-relative">
                <select class="form-select form-control" id="dailychart">
                    <option selected="">This Month</option>
                    <option value="aug">August</option>
                    <option value="jul">July</option>
                    <option value="jun">June</option>
                </select>
            </div>
        </div>
        <br>
        <section>
            <p>User ID :<span><?php echo $userrow["autogenerated_id"]; ?></span></p>
            <?php if ($_SESSION['User_TYPE'] == "Normal") { ?>
                <p>Refferals: :<span>
                                    <?php
                                    $query_ref = "SELECT * FROM signup WHERE referral_id = '" . $_SESSION["User_ID"] . "' ";
                                    $result_ref = mysqli_query($con, $query_ref);
                                    $num_ref = mysqli_num_rows($result_ref);
                                    ?>
                                    <?php echo $num_ref; ?>
                                </span>
                    <a href="refer.php">View All</a></p>
                <p>Registeration Date :<span> <?php echo date('l, d F, Y', strtotime($userrow['datetime'])); ?></span>
                </p>
            <?php } else { ?>
                <p>Registeration Date :<span> <?php echo date('l, d F, Y', strtotime($userrow['datetime'])); ?></span>
                </p>
                <?php
            }
            ?>

        </section>


        <?php
        if ($_SESSION["User_TYPE"] == "Normal") {
        $total_Invest = 0;
        $query_In = "SELECT * FROM user_invests WHERE iuserid = '" . $_SESSION["User_ID"] . "' ";
        $sql_In = mysqli_query($con, $query_In);
        while ($row_In = mysqli_fetch_array($sql_In)) {
            $total_Invest = $total_Invest + $row_In["iamount"];
        }
        $Remaining_Amount = $balance_row["total_user_amount"] - $total_Invest;
        ?>
        <div class="row row-cols-xl-5 row-cols-md-2 row-cols-1">
            <div class="col mt-4">
                <a href="#!"
                   class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                    <div class="d-flex align-items-center">
                        <div class=" text-center rounded-pill">
                            <i class="uil uil-usd-circle fs-4 mb-0"></i>
                        </div>
                        <div class="flex-1 ms-3">
                            <h6 class="mb-0 text-muted">Deposited</h6>
                            <p class="fs-5 text-dark fw-bold mb-0">
                                <span>PKR <?php $total = $balance_row["total_user_amount"];
                                    if ($total != "") echo round($total); else echo "0.00"; ?></span></p>
                        </div>
                    </div>


                </a>
            </div><!--end col-->
            <div class="col mt-4">
                <a href="#!"
                   class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                    <div class="d-flex align-items-center">
                        <div class=" text-center rounded-pill">
                            <i class="uil uil-usd-circle fs-4 mb-0"></i>
                        </div>
                        <div class="flex-1 ms-3">
                            <h6 class="mb-0 text-muted">Remaining</h6>
                            <p class="fs-5 text-dark fw-bold mb-0"><span>PKR <?php $total = $Remaining_Amount;
                                    if ($total != "") echo round($total); else echo "0.00"; ?></span></p>
                        </div>
                    </div>


                </a>
            </div>
            <div class="col mt-4">
                <a href="#!"
                   class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                    <div class="d-flex align-items-center">
                        <div class=" text-center rounded-pill">
                            <i class="uil uil-usd-circle fs-4 mb-0"></i>
                        </div>
                        <div class="flex-1 ms-3">
                            <h6 class="mb-0 text-muted">Invested</h6>
                            <p class="fs-5 text-dark fw-bold mb-0"><span>PKR <?php
                                    if ($total_Invest != "" && $total_Invest > 0) echo $total_Invest; else echo "0.00";
                                    ?></span></p>
                        </div>
                    </div>


                </a>
            </div>
            <div class="col mt-4">
                <a href="#!"
                   class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                    <div class="d-flex align-items-center">
                        <div class=" text-center rounded-pill">
                            <i class="uil uil-usd-circle fs-4 mb-0"></i>
                        </div>
                        <div class="flex-1 ms-3">
                            <h6 class="mb-0 text-muted">Total Income</h6>
                            <p class="fs-5 text-dark fw-bold mb-0"><span>PKR <?php $total = $Total_Earning;
                                    if ($total != "" && $total > 0) echo $total; else echo "0.00"; ?></span></p>
                        </div>
                    </div>


                </a>
            </div>
            <div class="col mt-4">
                <a href="#!"
                   class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                    <div class="d-flex align-items-center">
                        <div class=" text-center rounded-pill">
                            <i class="uil uil-usd-circle fs-4 mb-0"></i>
                        </div>
                        <div class="flex-1 ms-3">
                            <h6 class="mb-0 text-muted">Available</h6>
                            <p class="fs-5 text-dark fw-bold mb-0"><span>PKR <?php $total = $Remaining_Balance;
                                    if ($total != "" && $total > 0) echo $total; else echo "0.00"; ?></span></p>
                        </div>
                    </div>


                </a>
            </div>
            <?php
            } else {

            $query_special = "SELECT * FROM special_user_packages WHERE spackage_user = '" . $_SESSION["User_ID"] . "'";
            $sql_special = mysqli_query($con, $query_special);
            $row_special = mysqli_fetch_array($sql_special);

            $total_withdraw1 = 0;
            $query_withdraw1 = "SELECT * FROM withdraw WHERE w_user = '" . $_SESSION["User_ID"] . "' AND w_package = '0' AND w_status = 'Send'";
            $sql_withdraw1 = mysqli_query($con, $query_withdraw1);
            while ($row_withdraw1 = mysqli_fetch_array($sql_withdraw1)) {
                $total_withdraw1 = $total_withdraw1 + $row_withdraw1["w_amount"];
            }

            $total_withdraw1 = 0;
            $query_withdraw1 = "SELECT * FROM withdraw WHERE w_user = '" . $_SESSION["User_ID"] . "' AND w_package = '0' AND (w_status = 'Pending' OR w_status = 'Send')";
            $sql_withdraw1 = mysqli_query($con, $query_withdraw1);
            while ($row_withdraw1 = mysqli_fetch_array($sql_withdraw1)) {
                $total_withdraw1 = $total_withdraw1 + $row_withdraw1["w_amount"];
            }
            $Remaining_Balance = 0;
            $Remaining_Balance = $row_special["stotal_income"] - $total_withdraw1;

            ?>

            <div class="row row-cols-xl-5 row-cols-md-2 row-cols-1">
                <div class="col mt-4">
                    <a href="#!"
                       class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                        <div class="d-flex align-items-center">
                            <div class=" text-center rounded-pill">
                                <i class="uil uil-usd-circle fs-4 mb-0"></i>
                            </div>
                            <div class="flex-1 ms-3">
                                <h6 class="mb-0 text-muted">Deposited</h6>
                                <p class="fs-5 text-dark fw-bold mb-0">
                                    <span>PKR <?php $total = $balance_row["total_user_amount"];
                                        if ($total != "") echo round($total); else echo "0.00"; ?></span></p>
                            </div>
                        </div>


                    </a>
                </div><!--end col-->
                <div class="col mt-4">
                    <a href="#!"
                       class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                        <div class="d-flex align-items-center">
                            <div class=" text-center rounded-pill">
                                <i class="uil uil-usd-circle fs-4 mb-0"></i>
                            </div>
                            <div class="flex-1 ms-3">
                                <h6 class="mb-0 text-muted">Invested Amount</h6>
                                <p class="fs-5 text-dark fw-bold mb-0"><span>PKR  <?php
                                        $total_Invest = $row_special["sinvested_amount"];
                                        if ($total_Invest != "" && $total_Invest > 0) {
                                            echo $total_Invest;
                                        } else {
                                            echo "0.00";
                                        }
                                        ?>
                                                    </span>
                                </p>
                            </div>
                        </div>


                    </a>
                </div>
                <div class="col mt-4">
                    <a href="#!"
                       class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                        <div class="d-flex align-items-center">
                            <div class=" text-center rounded-pill">
                                <i class="uil uil-usd-circle fs-4 mb-0"></i>
                            </div>
                            <div class="flex-1 ms-3">
                                <h6 class="mb-0 text-muted">Total Income</h6>
                                <p class="fs-5 text-dark fw-bold mb-0">
                                    <span>PKR <?php $total = $row_special["stotal_income"];
                                        if ($total != "" && $total > 0) echo $total; else echo "0.00"; ?></span></p>
                            </div>
                        </div>


                    </a>
                </div>
                <div class="col mt-4">
                    <a href="#!"
                       class="features feature-primary d-flex justify-content-between align-items-center bg-white rounded shadow p-3">
                        <div class="d-flex align-items-center">
                            <div class=" text-center rounded-pill">
                                <i class="uil uil-usd-circle fs-4 mb-0"></i>
                            </div>
                            <div class="flex-1 ms-3">
                                <h6 class="mb-0 text-muted">Available</h6>
                                <p class="fs-5 text-dark fw-bold mb-0"><span>PKR <?php $total = $Remaining_Balance;
                                        if ($total != "" && $total > 0) echo $total; else echo "0.00"; ?></span></p>
                            </div>
                        </div>


                    </a>
                </div>
                <?php
                }
                ?>


            </div><!--end row-->


            <?php if ($_SESSION["User_TYPE"] == "Normal") { ?>
            <!-- Table Start -->
            <div class="col-12 mt-4" id="tables">
                <div class="component-wrapper bg-white rounded shadow">
                    <div class="p-4 border-bottom">
                        <h4 class="title mb-0"> Last Deposits </h4>
                    </div>

                    <div class="p-4">
                        <div class="table-responsive bg-white shadow rounded">
                            <table class="table mb-0 table-center">
                                <thead>
                                <tr>
                                    <th scope="col" class="border-bottom">SR No</th>
                                    <th scope="col" class="border-bottom">Date</th>
                                    <th scope="col" class="border-bottom">Balance Amount</th>
                                    <th scope="col" class="border-bottom">Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $Sr = 1;
                                $query_history = "SELECT * FROM user_amounts WHERE auserid='" . $_SESSION["User_ID"] . "' ORDER BY aid DESC";
                                $result_history = mysqli_query($con, $query_history);
                                while ($row_hisotry = mysqli_fetch_array($result_history)) {
                                    ?>
                                    <tr>
                                        <td><?= $Sr; ?></td>
                                        <td><?= date("d-m-Y", strtotime($row_hisotry["adatetime"])); ?></td>
                                        <td>PKR <?= number_format($row_hisotry["aamount"]) ?></td>
                                        <td><?= $row_hisotry["astatus"] ?></td>
                                        <td><?php if ($row_hisotry["admin_comment"] == "") {
                                            echo "No Comments";
                                        } else {
                                            echo $row_hisotry["admin_comment"];
                                        } ?></td>
                                    </tr>
                                    <?php
                                    $Sr++;
                                }
                                ?>
                                </tbody>
                            </table>
                            <?php
            } ?>
                        </div>
                    </div>
                </div>
            </div><!--end col-->
            <!-- Table End -->

        </div>
    </div><!--end container-->

    <!-- Footer Start -->
    <footer class="bg-white shadow py-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col">
                    <div class="text-sm-start text-center">
                        <p class="mb-0 text-muted">©
                            <script>document.write(new Date().getFullYear())</script>
                            Site
                        </p>
                    </div>
                </div><!--end col-->
            </div><!--end row-->
        </div><!--end container-->
    </footer><!--end footer-->
    <!-- End -->
    </main>
    <!--End page-content" -->
</div>
<!-- page-wrapper -->

<!-- Offcanvas Start -->
<div class="offcanvas offcanvas-end bg-white shadow" tabindex="-1" id="offcanvasRight"
     aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header border-bottom">
        <h5 id="offcanvasRightLabel" class="mb-0">
            <img src="assets/images/logo-dark.png" height="24" class="light-version" alt="">
            <img src="assets/images/logo-light.png" height="24" class="dark-version" alt="">
        </h5>
        <button type="button" class="btn-close d-flex align-items-center text-dark" data-bs-dismiss="offcanvas"
                aria-label="Close"><i class="mdi mdi-close fs-4"></i></button>
    </div>
    <div class="offcanvas-body p-4 px-md-5">
        <div class="row">
            <div class="col-12">
                <!-- Style switcher -->
                <div id="style-switcher">
                    <div>
                        <ul class="text-center list-unstyled mb-0">
                            <li class="d-grid"><a href="javascript:void(0)" class="rtl-version t-rtl-light"
                                                  onclick="setTheme('style-rtl')"><img src="assets/images/demos/rtl.png"
                                                                                       class="img-fluid rounded-md shadow-md d-block"
                                                                                       alt=""><span
                                            class="text-muted mt-2 d-block">RTL Version</span></a></li>
                            <li class="d-grid"><a href="javascript:void(0)" class="ltr-version t-ltr-light"
                                                  onclick="setTheme('style')"><img src="assets/images/demos/ltr.png"
                                                                                   class="img-fluid rounded-md shadow-md d-block"
                                                                                   alt=""><span
                                            class="text-muted mt-2 d-block">LTR Version</span></a></li>
                            <li class="d-grid"><a href="javascript:void(0)" class="dark-rtl-version t-rtl-dark"
                                                  onclick="setTheme('style-dark-rtl')"><img
                                            src="assets/images/demos/dark-rtl.png"
                                            class="img-fluid rounded-md shadow-md d-block" alt=""><span
                                            class="text-muted mt-2 d-block">RTL Version</span></a></li>
                            <li class="d-grid"><a href="javascript:void(0)" class="dark-ltr-version t-ltr-dark"
                                                  onclick="setTheme('style-dark')"><img
                                            src="assets/images/demos/dark.png"
                                            class="img-fluid rounded-md shadow-md d-block" alt=""><span
                                            class="text-muted mt-2 d-block">LTR Version</span></a></li>
                            <li class="d-grid"><a href="javascript:void(0)" class="dark-version t-dark mt-4"
                                                  onclick="setTheme('style-dark')"><img
                                            src="assets/images/demos/dark.png"
                                            class="img-fluid rounded-md shadow-md d-block" alt=""><span
                                            class="text-muted mt-2 d-block">Dark Version</span></a></li>
                            <li class="d-grid"><a href="javascript:void(0)" class="light-version t-light mt-4"
                                                  onclick="setTheme('style')"><img src="assets/images/demos/ltr.png"
                                                                                   class="img-fluid rounded-md shadow-md d-block"
                                                                                   alt=""><span
                                            class="text-muted mt-2 d-block">Light Version</span></a></li>
                            <li class="d-grid"><a href="../landing/index.php" target="_blank" class="mt-4"><img
                                            src="assets/images/demos/landing.png"
                                            class="img-fluid rounded-md shadow-md d-block" alt=""><span
                                            class="text-muted mt-2 d-block">Landing Demos</span></a></li>
                        </ul>
                    </div>
                </div>
                <!-- end Style switcher -->
            </div><!--end col-->
        </div>
    </div>

    <div class="offcanvas-footer p-3 border-top text-center">
        <ul class="list-unstyled social-icon mb-0">
            <li class="list-inline-item mb-0"><a href="https://1.envato.market/landrick" target="_blank"
                                                 class="rounded"><i class="ti ti-shopping-cart align-middle"
                                                                    title="Buy Now"></i></a></li>
            <li class="list-inline-item mb-0"><a href="https://dribbble.com/shreethemes" target="_blank"
                                                 class="rounded"><i class="ti ti-brand-dribbble align-middle"
                                                                    title="dribbble"></i></a></li>
            <li class="list-inline-item mb-0"><a href="https://www.facebook.com/shreethemes" target="_blank"
                                                 class="rounded"><i class="ti ti-brand-facebook align-middle"
                                                                    title="facebook"></i></a></li>
            <li class="list-inline-item mb-0"><a href="https://www.instagram.com/shreethemes/" target="_blank"
                                                 class="rounded"><i class="ti ti-brand-instagram align-middle"
                                                                    title="instagram"></i></a></li>
            <li class="list-inline-item mb-0"><a href="https://twitter.com/shreethemes" target="_blank" class="rounded"><i
                            class="ti ti-brand-twitter align-middle" title="twitter"></i></a></li>
            <li class="list-inline-item mb-0"><a href="mailto:support@shreethemes.in" class="rounded"><i
                            class="ti ti-mail align-middle" title="email"></i></a></li>
            <li class="list-inline-item mb-0"><a href="https://shreethemes.in" target="_blank" class="rounded"><i
                            class="ti ti-world align-middle" title="website"></i></a></li>
        </ul><!--end icon-->
    </div>
</div>
<!-- Offcanvas End -->

<!-- javascript -->
<script src="assets/js/bootstrap.bundle.min.js"></script>
<!-- simplebar -->
<script src="assets/js/simplebar.min.js"></script>
<!-- Icons -->
<script src="assets/js/feather.min.js"></script>
<!-- Chart -->
<script src="assets/js/apexcharts.min.js"></script>
<!-- Main Js -->
<script src="assets/js/plugins.init.js"></script>
<script src="assets/js/app.js"></script>

</body>

</html>